name: test-run

trainer:
  model_path: /notebooks/ComfyUI/models/checkpoints/sd_xl_base_1.0_0.9vae.safetensors
  batch_size: 4
  resolution: 1024
  seed: 1138
  wandb_id: ""
  use_ema: false
  use_xformers: false
  accumulate_grad_batches: 1
  gradient_clip_val: 0.0

  offset_noise: true
  offset_noise_val: 0.0375
  min_snr: false
  min_snr_val: 5

  checkpoint_dir: checkopint
  checkpoint_freq: 1
  save_weights_only: true
  max_epochs: 60
  max_steps: -1
  
lightning:
  accelerator: gpu
  devices: -1
  precision: bf16-true

cache:
  enabled: true
  cache_bsz: 8
  cache_dir: cache
  use_legacy_key: false
  target: ["images"] #[images, prompts]

dataset:
  img_path: "/tmp/VBP2-p1p2/_classified"
  tag_processor: data.processors.shuffle_prompts
  center_crop: false
  ucg: 0.1
  max_token_length: 150 # [75, 150, 225]
  debug_arb: false
  allow_duplicates: false

optimizer:
  # Note: To use adafactor, you need to disable scheduler
  # name: transformers.Adafactor
  # params: 
  #   relative_step: True
  name: bitsandbytes.optim.PagedAdamW8bit
  # layer_lr: 
  #   - '^input_blocks\.[0-8]\..*$': 5e-7
  #   - '^middle_block\.[0-2]\..*$': 5e-7
  #   - '^output_blocks\.[0-8]\..*$': 5e-7
  params:
    lr: 2e-6
    weight_decay: 1e-2

scheduler:
  name: transformers.get_constant_schedule_with_warmup
  params:
    num_warmup_steps: 100
    last_epoch: -1

sampling:
  enabled: true
  use_wandb: true
  every_n_steps: -1
  every_n_epochs: 1
  save_dir: "samples"
  seed: 1024
  height: 1024
  width: 1024
  steps: 28
  cfg_scale: 8
  negative_prompts: 
    - "lowres, bad anatomy, text, error, extra digit, cropped"
    - "lowres, low quality, text, error, extra digit, cropped"
    - "lowres, low quality, text, error, extra digit, cropped"
    - "lowres, low quality, text, error, extra digit, cropped"
    - "lowres, low quality, text, error, extra digit, cropped"
  prompts: 
    - "best quality, a girl with a yellow hat and a yellow shirt, sitting, white legwear, uniform, jacket, thighhighs, bare shoulders, high contrast, paint splatter"
    - "best quality, 1girl, solo, loli, cat girl, silver hair ,blue eyes, flat chest, solo, beautiful detailed background, messy hair, long hair"
    - "masterpiece, best quality, 1girl, solo,loli,wedding dress|see-through highleg leotard, veil, elbow gloves, white thighhighs, crown, earrings, bow on waist, sideboob, lace,"
    - "1girl, solo, shirt, thighhighs, skirt, hands on hips, white shirt, crystal, flandre scarlet, blonde hair, grey skirt, red bow, red eyes, black thighhighs, wings, white background,"
    - "1girl,sitting,fantasy,masterpiece,best quality,(long blonde hair),(blue eyes),(floating hair),(black ribbed sweater:1.1),(red plaid skirt:1.1),(cat ears)"

# arb config will be calculated automatically if not specified
# to override, uncomment and specify values
#
# arb:
#   enabled: false
#   debug: false
#   base_res: [512, 512]
#   max_size: [768, 512]
#   divisible: 64
#   max_ar_error: 4
#   min_dim: 256
#   dim_limit: 1024
#
# 
# lora:
#   enabled: false
#   rank: 16
#   conv_rank: 16
#   lora_alpha: 8
#   conv_alpha: 8
#   multipier: 1.0
#   unet_lr: 1e-4
#   dropout: 0.0