name: test-run

trainer:
  model_path: /notebooks/ComfyUI/models/checkpoints/sd_xl_base_0.9.safetensors
  batch_size: 4
  resolution: 1024
  seed: 1138
  wandb_id: "sdxl-test"
  
  use_ema: false
  use_xformers: false
  accumulate_grad_batches: 1
  gradient_clip_val: 0.0

  offset_noise: false
  offset_noise_val: 0.1
  min_snr: true
  min_snr_val: 5

  checkpoint_dir: checkopint
  checkpoint_freq: -1
  max_epochs: 40
  max_steps: -1

lightning:
  accelerator: gpu
  devices: -1
  precision: bf16-mixed

# 1024
arb:
  debug: false
  base_res: [1024, 1024]
  max_size: [1024, 1280]
  divisible: 64
  max_ar_error: 4
  min_dim: 384
  dim_limit:  1536

cache:
  enabled: false
  cache_bsz: 4
  cache_dir: cache
  target: ["images"] #[images, prompts]

dataset:
  img_path: 
    - "/notebooks/storage/datasets/momoko-fuji"
  center_crop: false
  ucg: 0.1
  debug_arb: false
  process_tags: true
  important_tags: []
  allow_duplicates: false

optimizer:
  name: bitsandbytes.optim.PagedAdamW8bit
  params:
    lr: 2e-6
    weight_decay: 1e-2

sampling:
  enabled: true
  use_wandb: true
  every_n_steps: -1
  every_n_epochs: 1
  save_dir: "samples"
  seed: 1024
  height: 1024
  width: 1024
  steps: 28
  cfg_scale: 8
  negative_prompts: 
    - "lowres, bad anatomy, text, error, extra digit, cropped"
    - "lowres, low quality, text, error, extra digit, cropped"
  prompts: 
    - "a girl running fast on the country lane"
    - "a girl in black serafuku standing in a field. Tags: solo, food, fruit, lemon, masterpiece"

  