name: test-run

trainer:
  model_path: /notebooks/ComfyUI/models/checkpoints/sd_xl_base_0.9.safetensors
  batch_size: 4
  resolution: 1024
  seed: 1138
  
  use_ema: false
  use_xformers: true
  accumulate_grad_batches: 1
  gradient_clip_val: 0.0

  offset_noise: false
  offset_noise_val: 0.1
  min_snr: true
  min_snr_val: 5

  checkpoint_dir: checkopint
  checkpoint_freq: 1
  max_epochs: 4
  max_steps: -1

lightning:
  accelerator: gpu
  devices: -1
  precision: bf16-mixed

# 1024
arb:
  enabled: true
  debug: false
  base_res: [1024, 1024]
  max_size: [1280, 1024]
  divisible: 64
  max_ar_error: 4
  min_dim: 640
  dim_limit: 1728

cache:
  enabled: true
  cache_bsz: 4
  cache_dir: cache

  # Not Implemented
  # target: [images, prompts]

dataset:
  img_path: 
    - "/notebooks/rurudo_lion"
  center_crop: false
  ucg: 0.1
  debug_arb: false
  num_workers: 3
  process_tags: true
  important_tags: []
  allow_duplicates: false

optimizer:
  # name: transformers.optimization.Adafactor
  # params: 
  #   relative_step: True
  name: bitsandbytes.optim.PagedAdamW8bit
  params:
    lr: 5e-6
    weight_decay: 1e-2
    eps: 1e-8

monitor:
  wandb_id: ""
  huggingface_repo: ""
  hf_auth_token: ""
  store_checkpoints: true

sampling:
  enabled: true
  use_wandb: true
  every_n_steps: -1
  every_n_epochs: 1
  save_dir: "samples"
  seed: 1139
  height: 1024
  width: 1024
  steps: 20
  cfg_scale: 9
  negative_prompts: 
    - "lowres, bad anatomy, text, error, extra digit, cropped"
    - "lowres, low quality"
  prompts: 
    - "a girl running fast on the country lane"
    - "a girl in black serafuku standing in a field. Tags: solo, food, fruit, lemon, masterpiece"

  