name: test-run

trainer:
  model_path: /notebooks/ComfyUI/models/checkpoints/sd_xl_base_1.0_0.9vae.safetensors
  batch_size: 4
  resolution: 1024
  seed: 1138
  wandb_id: ""
  use_ema: false
  use_xformers: false
  accumulate_grad_batches: 1
  gradient_clip_val: 0.0

  save_format: safetensors
  checkpoint_dir: checkopint
  checkpoint_freq: 1
  checkpoint_steps: -1
  save_weights_only: true
  max_epochs: 60
  max_steps: -1

advanced:
  offset_noise: true
  offset_noise_val: 0.0375
  min_snr_val: 5
  timestep_start: 0
  timestep_end: 1000
  input_perturbation: false
  input_perturbation_val: 0.0
  scale_v_pred_loss_like_noise_pred: false
  v_pred_like_loss: 0
  debiased_estimation_loss: false
  zero_terminal_snr: false
  
lightning:
  accelerator: gpu
  devices: -1
  precision: 16-mixed

dataset:
  img_path: "/notebooks/rurudo_lion_imgonly"
  tag_processor: data.processors.placebo
  center_crop: false
  ucg: 0.1
  max_token_length: 225 # [75, 150, 225]
  # repeat_strategy:
  #   - [/rurudo_lion_imgonly/, 2]

optimizer:
  name: bitsandbytes.optim.PagedLion8bit
  params:
    lr: 2e-6
    weight_decay: 1e-2
  # layer_lr: 
  #   - '^input_blocks\.[0-8]\..*$': 5e-7
  #   - '^middle_block\.[0-2]\..*$': 5e-7
  #   - '^output_blocks\.[0-8]\..*$': 5e-7

scheduler:
  name: transformers.get_constant_schedule_with_warmup
  params:
    num_warmup_steps: 100
    last_epoch: -1

sampling:
  enabled: false
  use_wandb: true
  every_n_steps: -1
  every_n_epochs: 1
  save_dir: "samples"
  seed: 1024
  height: 1024
  width: 1024
  steps: 28
  cfg_scale: 8
  negative_prompts: 
    - "lowres, bad anatomy, text, error, extra digit, cropped"
    - "lowres, low quality, text, error, extra digit, cropped"
    - "lowres, low quality, text, error, extra digit, cropped"
    - "lowres, low quality, text, error, extra digit, cropped"
    - "lowres, low quality, text, error, extra digit, cropped"
  prompts: 
    - "best quality, a girl with a yellow hat and a yellow shirt, sitting, white legwear, uniform, jacket, thighhighs, bare shoulders, high contrast, paint splatter"
    - "best quality, 1girl, solo, loli, cat girl, silver hair ,blue eyes, flat chest, solo, beautiful detailed background, messy hair, long hair"
    - "masterpiece, best quality, 1girl, solo,loli,wedding dress|see-through highleg leotard, veil, elbow gloves, white thighhighs, crown, earrings, bow on waist, sideboob, lace,"
    - "1girl, solo, shirt, thighhighs, skirt, hands on hips, white shirt, crystal, flandre scarlet, blonde hair, grey skirt, red bow, red eyes, black thighhighs, wings, white background,"
    - "1girl,sitting,fantasy,masterpiece,best quality,(long blonde hair),(blue eyes),(floating hair),(black ribbed sweater:1.1),(red plaid skirt:1.1),(cat ears)"
 
# lora:
#   enabled: true
#   rank: 16
#   lora_alpha: 8
#   multipier: 1.0
#   unet_lr: 1e-4