name: test-run
model_path: hydit_v1.2.pt
version: hydit_1.2 # hydit_v1.1, hydit_v1.2 
use_kdiffusion_loss: false
# clip_path: ...
# mt5_path: ...

trainer:
  precision: bf16-mixed
  batch_size: 4
  seed: 1138
  wandb_id: ""
  accumulate_grad_batches: 1
  gradient_clip_val: 0.0

  save_format: safetensors
  checkpoint_dir: checkpoint
  checkpoint_freq: 1
  checkpoint_steps: -1
  save_weights_only: true
  max_epochs: 1
  max_steps: -1

advanced:
  vae_encode_batch_size: -1 # same as batch_size
  train_text_encoder_1: false
  train_text_encoder_2: false
  text_encoder_1_lr: 3e-6
  text_encoder_2_lr: 3e-6
  min_snr: true
  min_snr_val: 5
  v_parameterization: false
  zero_terminal_snr: false

dataset:
  # store_cls: common.private_storage.ParquetImageClustered
  img_path: "/storage/dev/nyanko/niji-anime-1"

optimizer:
  name: bitsandbytes.optim.Lion8bit
  params:
    lr: 5e-6
    weight_decay: 1e-2

scheduler:
  name: transformers.get_constant_schedule_with_warmup
  params:
    num_warmup_steps: 0
    last_epoch: -1

sampling:
  enabled: false
  use_wandb: true
  seed: 42
  height: 1280
  width: 768
  every_n_steps: -1
  every_n_epochs: 1
  save_dir: "samples"
  prompts: 
    - "best quality, a girl with a yellow hat and a yellow shirt, sitting, white legwear, uniform, jacket, thighhighs, bare shoulders, high contrast, paint splatter"
    - "best quality, 1girl, solo, loli, cat girl, silver hair ,blue eyes, flat chest, solo, beautiful detailed background, messy hair, long hair"
    - "masterpiece, best quality, 1girl, solo,loli,wedding dress|see-through highleg leotard, veil, elbow gloves, white thighhighs, crown, earrings, bow on waist, sideboob, lace,"
    - "1girl, solo, shirt, thighhighs, skirt, hands on hips, white shirt, crystal, flandre scarlet, blonde hair, grey skirt, red bow, red eyes, black thighhighs, wings, white background,"
    - "1girl,sitting,fantasy,masterpiece,best quality,(long blonde hair),(blue eyes),(floating hair),(black ribbed sweater:1.1),(red plaid skirt:1.1),(cat ears)"
    - artist:ran'ou_(tamago_no_kimi), best quality, sensitive, 1girl, pointy ears, long hair, jewelry, looking at viewer, earrings, black gloves, thigh strap, bare shoulders, parted lips, underwear, see-through, off shoulder, bangs, mole on thigh, brown hair, on back, blue jacket, open clothes, pillow, barefoot, long sleeves, open jacket, eyebrows visible through hair, hands up, clothing cutout, half gloves, hot elf, black tight wear, pointed ears, lying down, highres, 2020s
    - best quality, 1girl, japanese clothes, wind chime, looking at viewer, smile, long hair, hair ornament, silver hair, white kimono, ponytail, hair between eyes, yukata, blue sky, floral print, bangs, hair flower, closed mouth, hair ribbon, long sleeves, looking back, alternate costume, signature, sidelocks, print kimono, white flower, blush, wide sleeves, red ribbon, cloudy sky, outdoors, 25-ji, Night Code de., Yoisaki Kanade, Project Sekai, absurdres, 2020s
    - best quality, 1girl, solo, loli, cat girl, silver hair ,blue eyes, flat chest, solo, beautiful detailed background, messy hair, long hair
    - masterpiece, best quality, 1girl, solo,loli,wedding dress|see-through highleg leotard, veil, elbow gloves, white thighhighs, crown, earrings, bow on waist, sideboob, lace
    - 1girl, solo, shirt, thighhighs, skirt, hands on hips, white shirt, crystal, flandre scarlet, blonde hair, grey skirt, red bow, red eyes, black thighhighs, wings, white background,
    - 1girl,sitting,fantasy,masterpiece,best quality,(long blonde hair),(blue eyes),(floating hair),(black ribbed sweater:1.1),(red plaid skirt:1.1),(cat ears)
