name: test-run

trainer:
  # model_url: https://pub-2fdef7a2969f43289c42ac5ae3412fd4.r2.dev/animesfw.tgz
  model_path: "/mnt/data/model-diffusers/sfw-model-unpacked"
  batch_size: 1
  gradient_checkpointing: true
  clip_skip: 2
  seed: 1138

  use_ema: false
  use_hivemind: false
  lr_scale: sqrt
  train_text_encoder: false
  attention_slicing: false
  vae_slicing: true

  offset_noise: false
  offset_noise_val: 0.1
  min_snr: false
  min_snr_val: 5

  # note: only works with init_batch_size > 1
  use_xformers: true

checkpoint:
  monitor: 'epoch'
  dirpath: /mnt/data/test-run/
  filename: 'sample-nd-epoch{epoch:02d}-loss{train_loss:.2f}'
  auto_insert_metric_name: false
  every_n_epochs: 10
  save_top_k: -1
  mode: 'max'
  save_last: false

lightning:
  accelerator: gpu
  devices: -1
  auto_select_gpus: true
  # limit_train_batches: 100
  max_epochs: 200
  precision: 32
  log_every_n_steps: 1
  accumulate_grad_batches: 1
  gradient_clip_val: 0.0
  auto_scale_batch_size: false
  auto_lr_find: false
  move_metrics_to_cpu: true

# arb:
#   enabled: true
#   debug: false
#   base_res: [512, 512]
#   max_size: [768, 512]
#   divisible: 64
#   max_ar_error: 4
#   min_dim: 256
#   dim_limit: 1024

dataset:
  ucg: 0.1
  debug_arb: false
  num_workers: 2
  process_tags: true
  root_path: /mnt/data/sd-dataset/test.lantent.h5
  prompt_processor: null
  enable_mask: true
  use_central_crop: False
  base_len: 512
  max_len: 1024
  augmentation:
    rotate: [-4,4]
    flip: true

optimizer:
  name: bitsandbytes.optim.AdamW8bit
  params:
    lr: 1e-6
    weight_decay: 1e-2
    eps: 1e-8

lr_scheduler:
  name: torch.optim.lr_scheduler.CosineAnnealingLR
  warmup: 
    enabled: false
    init_lr: 2e-8
    num_warmup: 50
    strategy: "cos"
  params:
    T_max: 20
    eta_min: 1e-7
    last_epoch: -1

monitor:
  wandb_id: ""
  huggingface_repo: ""
  hf_auth_token: ""
  store_checkpoints: false

sampling:
  enabled: false
  use_wandb: true
  every_n_steps: -1
  every_n_epochs: 10
  save_dir: "samples"
  seed: 1139
  height: 512
  width: 512
  steps: 20
  cfg_scale: 9
  negative_prompts: 
    - "lowres, bad anatomy, text, error, extra digit, cropped"
    - "lowres, low quality"
  prompts: 
    - "a girl running fast on the country lane"
    - "a girl in black serafuku standing in a field. Tags: solo, food, fruit, lemon, masterpiece"

encoder:
  # Leave blank to load from model
  text: 
  vae: /mnt/data/model-diffusers/sd14
  