name: test-run

trainer:
  model_path: /notebooks/ComfyUI/models/checkpoints/sd_xl_base_0.9.safetensors
  batch_size: 1
  resolution: 1024
  center_crop: false
  gradient_checkpointing: true
  clip_skip: 2
  seed: 1138
  use_ema: false
  use_hivemind: false
  lr_scale: sqrt
  train_text_encoder: false
  mixed_precision: false

  offset_noise: false
  offset_noise_val: 0.1
  min_snr: false
  min_snr_val: 5

  # note: only works with init_batch_size > 1
  use_xformers: true

checkpoint:
  monitor: 'epoch'
  dirpath: checkpoint
  filename: 'sample-nd-epoch{epoch:02d}-loss{train_loss:.2f}'
  auto_insert_metric_name: false
  every_n_epochs: 10
  save_top_k: 10
  mode: 'max'
  save_last: false

lightning:
  accelerator: gpu
  devices: -1
  auto_select_gpus: true
  # limit_train_batches: 100
  max_epochs: 20
  precision: bf16
  strategy: ddp_find_unused_parameters_false
  log_every_n_steps: 1
  accumulate_grad_batches: 1
  gradient_clip_val: 0.0

# 1024
arb:
  enabled: true
  debug: false
  base_res: [1024, 1024]
  max_size: [1280, 1024]
  divisible: 64
  max_ar_error: 4
  min_dim: 640
  dim_limit: 1728

cache:
  enabled: false
  cache_bsz: 4
  cache_dir: cache

  # Not Implemented
  # target: [images, prompts]

dataset:
  img_path: 
    - "/notebooks/storage/datasets/momoko-fuji"
  center_crop: false
  ucg: 0.1
  debug_arb: false
  num_workers: 3
  process_tags: true
  important_tags: []
  allow_duplicates: false

optimizer:
  name: bitsandbytes.optim.AdamW
  params:
    lr: 5e-6
    weight_decay: 1e-2
    eps: 1e-8

lr_scheduler:
  name: torch.optim.lr_scheduler.CosineAnnealingLR
  warmup: 
    enabled: false
    init_lr: 2e-8
    num_warmup: 50
    strategy: "cos"
  params:
    T_max: 20
    eta_min: 1e-7
    last_epoch: -1

monitor:
  wandb_id: ""
  huggingface_repo: ""
  hf_auth_token: ""
  store_checkpoints: true

sampling:
  enabled: false
  use_wandb: true
  every_n_steps: -1
  every_n_epochs: 1
  save_dir: "samples"
  seed: 1139
  height: 512
  width: 512
  steps: 20
  cfg_scale: 9
  negative_prompts: 
    - "lowres, bad anatomy, text, error, extra digit, cropped"
    - "lowres, low quality"
  prompts: 
    - "a girl running fast on the country lane"
    - "a girl in black serafuku standing in a field. Tags: solo, food, fruit, lemon, masterpiece"

  