name: test-run

trainer:
  model_path: "model"
  batch_size: 1
  resolution: 512
  center_crop: false
  seed: 1138
  use_ema: true
  use_hivemind: false
  use_xformers: false
  lr_scale: sqrt
  train_text_encoder: false
  attention_slicing: false
  vae_slicing: true

  offset_noise: false
  offset_noise_val: 0.1
  min_snr: false
  min_snr_val: 5
  
checkpoint:
  monitor: 'epoch'
  dirpath: checkpoint
  filename: 'sample-nd-epoch{epoch:02d}-loss{train_loss:.2f}'
  auto_insert_metric_name: false
  every_n_epochs: 3
  save_top_k: 5
  mode: 'max'
  save_last: true

lightning:
  accelerator: gpu
  devices: -1
  auto_select_gpus: true
  # limit_train_batches: 100
  max_epochs: 20
  precision: 16
  log_every_n_steps: 1
  accumulate_grad_batches: 1
  gradient_clip_val: 0

arb:
  enabled: true
  debug: false
  base_res: [512, 512]
  max_size: [768, 512]
  divisible: 64
  max_ar_error: 4
  min_dim: 256
  dim_limit: 1024

dataset:
  img_path: 
    - "https://pub-2fdef7a2969f43289c42ac5ae3412fd4.r2.dev/mmk.tgz"
  center_crop: false
  ucg: 0.0
  debug_arb: false
  num_workers: 3
  process_tags: true
  important_tags: []
  allow_duplicates: false

optimizer:
  name: torch.optim.AdamW
  params:
    lr: 5e-6
    weight_decay: 1e-2
    eps: 1e-8

lr_scheduler:
  name: torch.optim.lr_scheduler.CosineAnnealingLR
  warmup: 
    enabled: false
    init_lr: 2e-8
    num_warmup: 50
    strategy: "cos"
  params:
    T_max: 20
    eta_min: 1e-7
    last_epoch: -1

monitor:
  wandb_id: ""
  huggingface_repo: ""
  hf_auth_token: ""
  store_checkpoints: true

sampling:
  enabled: true
  use_wandb: true
  every_n_steps: -1
  every_n_epochs: 1
  save_dir: "samples"
  seed: 1139
  height: 512
  width: 512
  steps: 20
  cfg_scale: 9
  negative_prompts: 
    - "lowres, bad anatomy, text, error, extra digit, cropped"
    - "lowres, low quality"
  prompts: 
    - "a girl running fast on the country lane"
    - "a girl in black serafuku standing in a field. Tags: solo, food, fruit, lemon, masterpiece"
